import type { UserProfile, Match, Post } from './types';

export const mockProfiles: UserProfile[] = [
  {
    id: '1',
    name: 'Elif',
    age: 28,
    images: [
      'https://picsum.photos/seed/bematch1/600/800',
      'https://picsum.photos/seed/bematch1a/600/800',
    ],
    bio: 'Kahve ve seyahat tutkunu. Yeni yerler keşfetmeyi ve güzel anılar biriktirmeyi seviyorum.',
    interests: ['Seyahat', 'Fotoğrafçılık', 'Yoga'],
  },
  {
    id: '2',
    name: 'Can',
    age: 32,
    images: [
      'https://picsum.photos/seed/bematch2/600/800',
      'https://picsum.photos/seed/bematch2a/600/800',
    ],
    bio: 'Doğa yürüyüşleri ve kamp yapmaktan hoşlanan bir maceraperest. Hafta sonları genelde dağlardayım.',
    interests: ['Doğa Yürüyüşü', 'Kamp', 'Gitar'],
  },
  {
    id: '3',
    name: 'Selin',
    age: 25,
    images: [
      'https://picsum.photos/seed/bematch3/600/800',
      'https://picsum.photos/seed/bematch3a/600/800',
    ],
    bio: 'Sanat ve edebiyat aşığı. Boş zamanlarımda resim yapar, kitap okurum.',
    interests: ['Sanat', 'Kitaplar', 'Müze'],
  },
  {
    id: '4',
    name: 'Emre',
    age: 30,
    images: [
      'https://picsum.photos/seed/bematch4/600/800',
    ],
    bio: 'Teknoloji ve oyun meraklısı. Birlikte oynayabileceğimiz birini arıyorum.',
    interests: ['Oyun', 'Teknoloji', 'Sinema'],
  },
  {
    id: '5',
    name: 'Buse',
    age: 29,
    images: [
      'https://picsum.photos/seed/bematch5/600/800',
      'https://picsum.photos/seed/bematch5a/600/800',
      'https://picsum.photos/seed/bematch5b/600/800',
    ],
    bio: 'Hayvanları çok seviyorum, özellikle köpekleri. Sahilde uzun yürüyüşler favorim.',
    interests: ['Hayvanlar', 'Plaj', 'Yemek Yapmak'],
  },
];

export const mockMatches: Match[] = [
  {
    id: 'match1',
    userId: '1',
    name: 'Elif',
    avatarUrl: 'https://picsum.photos/seed/bematch1/100/100',
    lastMessage: 'Selam! Nasılsın?',
    lastMessageTimestamp: new Date(Date.now() - 1000 * 60 * 5),
  },
  {
    id: 'match2',
    userId: '3',
    name: 'Selin',
    avatarUrl: 'https://picsum.photos/seed/bematch3/100/100',
    lastMessage: 'Bu hafta sonu bir planın var mı?',
    lastMessageTimestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
  },
  {
    id: 'match3',
    userId: '5',
    name: 'Buse',
    avatarUrl: 'https://picsum.photos/seed/bematch5/100/100',
    lastMessage: 'Fotoğrafların çok güzel :)',
    lastMessageTimestamp: new Date(Date.now() - 1000 * 60 * 60 * 24),
  },
];


export const mockPosts: Post[] = [
    {
      id: 'post1',
      username: 'Elif',
      userAvatar: 'https://picsum.photos/seed/bematch1/100/100',
      imageUrl: 'https://picsum.photos/seed/post1/600/700',
      caption: 'What a wonderful day in Paris! Seeing the Eiffel Tower was incredible. 🗼 #travel #paris #tbt',
      language: 'en',
      likes: 1245,
      comments: 89,
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3),
    },
    {
      id: 'post-text-es',
      username: 'Javier',
      userAvatar: 'https://picsum.photos/seed/javier/100/100',
      caption: 'El fútbol es más que un juego, es una pasión que une a millones. ¿Cuál es tu equipo favorito? ⚽️',
      language: 'es',
      likes: 540,
      comments: 92,
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8),
    },
    {
      id: 'post-text-tr',
      username: 'Emre',
      userAvatar: 'https://picsum.photos/seed/bematch4/100/100',
      caption: 'Yazılım geliştirirken doğru müzik listesini bulmak, verimliliği en az %50 artırıyor. Sizin favori "kodlama" çalma listeniz hangisi? 👨‍💻🎶',
      language: 'tr',
      likes: 312,
      comments: 54,
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 12),
    },
    {
      id: 'post2',
      username: 'Can',
      userAvatar: 'https://picsum.photos/seed/bematch2/100/100',
      imageUrl: 'https://picsum.photos/seed/post2/600/600',
      caption: 'Campfire and stars this weekend... Nothing else needed. 🏕️🔥',
      language: 'en',
      likes: 832,
      comments: 45,
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 22),
    },
     {
      id: 'post3',
      username: 'Selin',
      userAvatar: 'https://picsum.photos/seed/bematch3/100/100',
      imageUrl: 'https://picsum.photos/seed/post3/600/750',
      caption: 'Yeni tablom sonunda bitti. Renklerle oynamayı seviyorum. 🎨 #sanat #resim #yağlıboya',
      language: 'tr',
      likes: 2400,
      comments: 212,
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 50),
    },
    {
      id: 'post-text-fr',
      username: 'Amélie',
      userAvatar: 'https://picsum.photos/seed/amelie/100/100',
      caption: 'La vie est faite de petits bonheurs. Un croissant chaud le matin, un bon livre, un sourire partagé. 🥐❤️',
      language: 'fr',
      likes: 1800,
      comments: 150,
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 55),
    },
    {
      id: 'post-text-en',
      username: 'John',
      userAvatar: 'https://picsum.photos/seed/john/100/100',
      caption: 'A Sunday morning classic: a hot coffee, a good book, and some light music in the background. Sometimes happiness is this simple. ☕️📖',
      language: 'en',
      likes: 950,
      comments: 130,
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 60),
    },
     {
      id: 'post4',
      username: 'Buse',
      userAvatar: 'https://picsum.photos/seed/bematch5/100/100',
      imageUrl: 'https://picsum.photos/seed/post4/600/600',
      caption: 'Sahilde köpeğimle sabah yürüyüşü gibisi yok. 🐾❤️',
      language: 'tr',
      likes: 987,
      comments: 61,
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 72),
    },
    {
      id: 'post-text-jp',
      username: 'Yuki',
      userAvatar: 'https://picsum.photos/seed/yuki/100/100',
      caption: '今日の天気は最高です！公園で散歩して、心も体もリフレッシュしました。桜がとても綺麗でした。🌸 (Bugünün havası harika! Parkta yürüyüş yapıp zihnimi ve bedenimi tazeledim. Kiraz çiçekleri çok güzeldi.)',
      language: 'ja',
      likes: 4500,
      comments: 320,
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 80),
    },
]
