
import type { Post, UserProfile } from './types';

// mockProfiles and mockMatches are no longer needed as we use Firestore.

export const mockPosts: Post[] = [
    {
      id: 'post1',
      username: 'Elif',
      userAvatar: 'https://picsum.photos/seed/bematch1/100/100',
      imageUrl: 'https://picsum.photos/seed/post1/600/700',
      caption: 'What a wonderful day in Paris! Seeing the Eiffel Tower was incredible. 🗼 #travel #paris #tbt',
      language: 'en',
      likes: 1245,
      comments: 89,
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3),
    },
    {
      id: 'post-text-es',
      username: 'Javier',
      userAvatar: 'https://picsum.photos/seed/javier/100/100',
      caption: 'El fútbol es más que un juego, es una pasión que une a millones. ¿Cuál es tu equipo favorito? ⚽️',
      language: 'es',
      likes: 540,
      comments: 92,
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8),
    },
    {
      id: 'post-text-tr',
      username: 'Emre',
      userAvatar: 'https://picsum.photos/seed/bematch4/100/100',
      caption: 'Yazılım geliştirirken doğru müzik listesini bulmak, verimliliği en az %50 artırıyor. Sizin favori "kodlama" çalma listeniz hangisi? 👨‍💻🎶',
      language: 'tr',
      likes: 312,
      comments: 54,
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 12),
    },
    {
      id: 'post2',
      username: 'Can',
      userAvatar: 'https://picsum.photos/seed/bematch2/100/100',
      imageUrl: 'https://picsum.photos/seed/post2/600/600',
      caption: 'Campfire and stars this weekend... Nothing else needed. 🏕️🔥',
      language: 'en',
      likes: 832,
      comments: 45,
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 22),
    },
     {
      id: 'post3',
      username: 'Selin',
      userAvatar: 'https://picsum.photos/seed/bematch3/100/100',
      imageUrl: 'https://picsum.photos/seed/post3/600/750',
      caption: 'Yeni tablom sonunda bitti. Renklerle oynamayı seviyorum. 🎨 #sanat #resim #yağlıboya',
      language: 'tr',
      likes: 2400,
      comments: 212,
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 50),
    },
    {
      id: 'post-text-fr',
      username: 'Amélie',
      userAvatar: 'https://picsum.photos/seed/amelie/100/100',
      caption: 'La vie est faite de petits bonheurs. Un croissant chaud le matin, un bon livre, un sourire partagé. 🥐❤️',
      language: 'fr',
      likes: 1800,
      comments: 150,
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 55),
    },
    {
      id: 'post-text-en',
      username: 'John',
      userAvatar: 'https://picsum.photos/seed/john/100/100',
      caption: 'A Sunday morning classic: a hot coffee, a good book, and some light music in the background. Sometimes happiness is this simple. ☕️📖',
      language: 'en',
      likes: 950,
      comments: 130,
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 60),
    },
     {
      id: 'post4',
      username: 'Buse',
      userAvatar: 'https://picsum.photos/seed/bematch5/100/100',
      imageUrl: 'https://picsum.photos/seed/post4/600/600',
      caption: 'Sahilde köpeğimle sabah yürüyüşü gibisi yok. 🐾❤️',
      language: 'tr',
      likes: 987,
      comments: 61,
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 72),
    },
    {
      id: 'post-text-jp',
      username: 'Yuki',
      userAvatar: 'https://picsum.photos/seed/yuki/100/100',
      caption: '今日の天気は最高です！公園で散歩して、心も体もリフレッシュしました。桜がとても綺麗でした。🌸 (Bugünün havası harika! Parkta yürüyüş yapıp zihnimi ve bedenimi tazeledim. Kiraz çiçekleri çok güzeldi.)',
      language: 'ja',
      likes: 4500,
      comments: 320,
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 80),
    },
];

export const mockProfiles: UserProfile[] = [
    {
      id: 'mock-1',
      uid: 'mock-1',
      fullName: 'Aslı',
      dateOfBirth: '1995-03-15',
      images: ['https://picsum.photos/seed/mock1/600/800'],
      bio: 'Gezmeyi, yeni yerler keşfetmeyi ve lezzetli yemekler tatmayı severim. Maceraya her zaman hazırım!',
      interests: ['seyahat', 'yemek', 'fotoğrafçılık'],
      gender: 'female',
    },
    {
      id: 'mock-2',
      uid: 'mock-2',
      fullName: 'Berk',
      dateOfBirth: '1992-08-22',
      images: ['https://picsum.photos/seed/mock2/600/800', 'https://picsum.photos/seed/mock2_2/600/800'],
      bio: 'Hafta sonları bisiklete biner, hafta içi kod yazarım. İyi bir kahve ve iyi bir sohbet her zaman günümü güzelleştirir.',
      interests: ['bisiklet', 'yazılım', 'kahve'],
      gender: 'male',
    },
    {
      id: 'mock-3',
      uid: 'mock-3',
      fullName: 'Ceyda',
      dateOfBirth: '1998-11-05',
      images: ['https://picsum.photos/seed/mock3/600/800'],
      bio: 'Sanat galerilerini gezmek, film eleştirileri okumak ve kedimle vakit geçirmek en büyük keyfim.',
      interests: ['sanat', 'sinema', 'hayvanlar'],
      gender: 'female',
    },
    {
      id: 'mock-4',
      uid: 'mock-4',
      fullName: 'Deniz',
      dateOfBirth: '1994-06-30',
      images: ['https://picsum.photos/seed/mock4/600/800', 'https://picsum.photos/seed/mock4_2/600/800', 'https://picsum.photos/seed/mock4_3/600/800'],
      bio: 'Müziğin ritmiyle yaşarım. Konserlere gitmek ve yeni gruplar keşfetmek vazgeçilmezim.',
      interests: ['müzik', 'konser', 'dans'],
      gender: 'other',
    },
];
